DROP TABLE IF EXISTS BOOKS;

CREATE TABLE BOOKS (
	BOOK_ID SERIAL PRIMARY KEY,
	TITLE VARCHAR(100),
	AUTHOR VARCHAR(50),
	GENRE VARCHAR(50),
	PUBLISHED_YEAR INT,
	PRICE DECIMAL(10, 2),
	STOCK INT
);

COPY BOOKS (
	BOOK_ID,
	TITLE,
	AUTHOR,
	GENRE,
	PUBLISHED_YEAR,
	PRICE,
	STOCK
)
FROM
	'C:\Users\KIIT\Desktop\Books.csv' DELIMITER ',' CSV HEADER;

SELECT
	*
FROM
	BOOKS;

DROP TABLE IF EXISTS CUSTOMERS;

CREATE TABLE CUSTOMERS (
	CUSTOMER_ID SERIAL PRIMARY KEY,
	NAME VARCHAR(100),
	EMAIL VARCHAR(100),
	PHONE VARCHAR(15),
	CITY VARCHAR(100),
	COUNTRY VARCHAR(150)
);

COPY CUSTOMERS (CUSTOMER_ID, NAME, EMAIL, PHONE, CITY, COUNTRY)
FROM
	'C:\Users\KIIT\Desktop\Customers.csv' DELIMITER ',' CSV HEADER;

SELECT
	*
FROM
	CUSTOMERS;

DROP TABLE IF EXISTS ORDERS;

CREATE TABLE ORDERS (
	ORDER_ID SERIAL PRIMARY KEY,
	CUSTOMER_ID INT REFERENCES CUSTOMERS (CUSTOMER_ID),
	BOOK_ID INT REFERENCES BOOKS (BOOK_ID),
	ORDER_DATE DATE,
	QUANTITY INT,
	TOTAL_AMOUNT NUMERIC
);

COPY ORDERS (
	ORDER_ID,
	CUSTOMER_ID,
	BOOK_ID,
	ORDER_DATE,
	QUANTITY,
	TOTAL_AMOUNT
)
FROM
	'C:\Users\KIIT\Desktop\Orders.csv' DELIMITER ',' CSV HEADER;

SELECT
	*
FROM
	ORDERS;

SELECT
	*
FROM
	BOOKS;

SELECT
	*
FROM
	CUSTOMERS;

-- 1) Retrieve all books in the "Fiction" genre:
SELECT
	*
FROM
	BOOKS
WHERE
	GENRE = 'Fiction';

-- 2) Find books published after the year 1950:
SELECT
	*
FROM
	BOOKS
WHERE
	PUBLISHED_YEAR > 1950;

-- 3) List all customers from the Canada:
SELECT
	*
FROM
	CUSTOMERS
WHERE
	COUNTRY = 'Canada';

-- 4) Show orders placed in November 2023:
SELECT
	*
FROM
	ORDERS
WHERE
	ORDER_DATE BETWEEN '2023-11-01' AND '2023-11-30';

-- 5) Retrieve the total stock of books available:
SELECT
	SUM(STOCK) AS TOTAL_STOCK
FROM
	BOOKS;

-- 6) Find the details of the most expensive book:
SELECT
	*
FROM
	BOOKS
ORDER BY
	PRICE DESC;

SELECT
	*
FROM
	BOOKS
ORDER BY
	PRICE DESC
LIMIT
	1;

-- 7) Show all customers who ordered more than 1 quantity of a book:
SELECT
	*
FROM
	ORDERS
WHERE
	QUANTITY > 1;

-- 8) Retrieve all orders where the total amount exceeds $20:
SELECT
	*
FROM
	ORDERS
WHERE
	TOTAL_AMOUNT > 20;

-- 9) List all genres available in the Books table:
SELECT DISTINCT
	GENRE
FROM
	BOOKS;

-- 10) Find the book with the lowest stock:
SELECT
	*
FROM
	BOOKS
ORDER BY
	STOCK ASC;

-- 11) Calculate the total revenue generated from all orders:
SELECT
	SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM
	ORDERS;

-- Advance Questions : 
-- Retrieve the total number of books sold for each genre:
SELECT
	B.GENRE,
	SUM(O.QUANTITY)
FROM
	ORDERS O
	JOIN BOOKS B ON O.BOOK_ID = B.BOOK_ID
GROUP BY
	B.GENRE;

--Find the average price of books in the "Fantasy" genre:
SELECT
	AVG(PRICE) AS AVG_FANTASY
FROM
	BOOKS
WHERE
	GENRE = 'Fantasy';

-- List customers who have placed at least 2 orders:
SELECT
	C.NAME,
	O.CUSTOMER_ID,
	COUNT(O.ORDER_ID) AS ORDER_COUNT
FROM
	CUSTOMERS C
	JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY
	C.NAME,
	O.CUSTOMER_ID
HAVING
	COUNT(O.ORDER_ID) >= 2;

--Find the most frequently ordered book:
SELECT
	O.BOOK_ID,
	B.TITLE,
	COUNT(O.ORDER_ID) AS FREQUENT_ORDER
FROM
	ORDERS O
	JOIN BOOKS B ON O.BOOK_ID = B.BOOK_ID
GROUP BY
	O.BOOK_ID,
	B.TITLE
ORDER BY
	FREQUENT_ORDER DESC;

SELECT
	BOOK_ID,
	COUNT(ORDER_ID) AS FREQUENT_ORDER
FROM
	ORDERS
GROUP BY
	BOOK_ID
ORDER BY
	FREQUENT_ORDER DESC;

--Show the top 3 most expensive books of 'Fantasy' Genre :
SELECT
	*
FROM
	BOOKS
WHERE
	GENRE = 'Fantasy'
ORDER BY
	PRICE DESC
LIMIT
	3;

--Retrieve the total quantity of books sold by each author:
SELECT
	B.AUTHOR,
	SUM(O.QUANTITY) AS BOOK_SOLD
FROM
	BOOKS B
	JOIN ORDERS O ON B.BOOK_ID = O.BOOK_ID
GROUP BY
	B.AUTHOR;

--List the cities where customers who spent over $30 are located:
SELECT DISTINCT
	C.CITY,
	TOTAL_AMOUNT
FROM
	ORDERS O
	JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
WHERE
	O.TOTAL_AMOUNT > 30
ORDER BY
	O.TOTAL_AMOUNT;

-- Find the top 3 best-selling books per genre using a Window Function
SELECT
	GENRE,
	TITLE,
	TOTAL_SOLD
FROM
	(
		SELECT
			B.GENRE,
			B.TITLE,
			SUM(O.QUANTITY) AS TOTAL_SOLD,
			RANK() OVER (
				PARTITION BY
					B.GENRE
				ORDER BY
					SUM(O.QUANTITY) DESC
			) AS RANK
		FROM
			BOOKS B
			JOIN ORDERS O ON B.BOOK_ID = O.BOOK_ID
		GROUP BY
			B.GENRE,
			B.TITLE
	) AS RANKED_BOOKS
WHERE
	RANK <= 3;

-- Calculate percentage contribution of each customer to total revenue
WITH
	TOTALREVENUE AS (
		SELECT
			SUM(TOTAL_AMOUNT) AS GRAND_TOTAL
		FROM
			ORDERS
	)
SELECT
	C.NAME,
	SUM(O.TOTAL_AMOUNT) AS CUSTOMER_SPEND,
	ROUND((SUM(O.TOTAL_AMOUNT) / TR.GRAND_TOTAL) * 100, 2) AS CONTRIBUTION_PERCENTAGE
FROM
	CUSTOMERS C
	JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
	CROSS JOIN TOTALREVENUE TR
GROUP BY
	C.NAME,
	TR.GRAND_TOTAL
ORDER BY
	CONTRIBUTION_PERCENTAGE DESC;

-- 8) Find the customer who spent the most on orders:
SELECT
	C.NAME,
	SUM(O.TOTAL_AMOUNT) AS MOST_SPENT
FROM
	ORDERS O
	JOIN CUSTOMERS C ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY
	C.NAME
ORDER BY
	MOST_SPENT DESC;

--Calculate the stock remaining after fulfilling all orders:
SELECT
	B.BOOK_ID,
	B.TITLE,
	B.STOCK,
	COALESCE(SUM(O.QUANTITY), 0) AS ORDER_QUANTITY,
	B.STOCK - COALESCE(SUM(O.QUANTITY), 0) AS REMAINING_QUANTITY
FROM
	BOOKS B
	LEFT JOIN ORDERS O ON B.BOOK_ID = O.BOOK_ID
GROUP BY
	B.BOOK_ID
ORDER BY
	B.BOOK_ID;

--Divide customers into 4 spending tiers (Quartiles) based on total purchase amount.
WITH
	CUSTOMER_SPENDING AS (
		SELECT
			C.CUSTOMER_ID,
			C.NAME,
			SUM(O.TOTAL_AMOUNT) AS TOTAL_SPENT
		FROM
			CUSTOMERS C
			JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
		GROUP BY
			C.CUSTOMER_ID,
			C.NAME
	)
SELECT
	CUSTOMER_ID,
	NAME,
	TOTAL_SPENT,
	NTILE(4) OVER (
		ORDER BY
			TOTAL_SPENT DESC
	) AS SPENDING_TIER
FROM
	CUSTOMER_SPENDING;

--What is the monthly revenue trend and growth rate?
WITH
	MONTHLY_REVENUE AS (
		SELECT
			DATE_TRUNC('month', ORDER_DATE) AS MONTH,
			SUM(TOTAL_AMOUNT) AS REVENUE
		FROM
			ORDERS
		GROUP BY
			MONTH
	)
SELECT
	MONTH,
	REVENUE,
	LAG(REVENUE) OVER (
		ORDER BY
			MONTH
	) AS PREVIOUS_MONTH,
	ROUND(
		(
			(
				REVENUE - LAG(REVENUE) OVER (
					ORDER BY
						MONTH
				)
			) / LAG(REVENUE) OVER (
				ORDER BY
					MONTH
			)
		) * 100,
		2
	) AS GROWTH_PERCENTAGE
FROM
	MONTHLY_REVENUE;

--Find Books Contributing to 80% of Total Revenue 
WITH
	BOOK_REVENUE AS (
		SELECT
			B.BOOK_ID,
			B.TITLE,
			SUM(O.TOTAL_AMOUNT) AS REVENUE
		FROM
			ORDERS O
			JOIN BOOKS B ON O.BOOK_ID = B.BOOK_ID
		GROUP BY
			B.BOOK_ID,
			B.TITLE
	),
	RANKED_BOOKS AS (
		SELECT
			*,
			SUM(REVENUE) OVER (
				ORDER BY
					REVENUE DESC
			) AS RUNNING_TOTAL,
			SUM(REVENUE) OVER () AS GRAND_TOTAL
		FROM
			BOOK_REVENUE
	)
SELECT
	*
FROM
	RANKED_BOOKS
WHERE
	RUNNING_TOTAL <= 0.8 * GRAND_TOTAL;

--Identify Customer Purchase Frequency & Retention Category
WITH
	ORDER_COUNTS AS (
		SELECT
			CUSTOMER_ID,
			COUNT(ORDER_ID) AS TOTAL_ORDERS
		FROM
			ORDERS
		GROUP BY
			CUSTOMER_ID
	)
SELECT
	CUSTOMER_ID,
	TOTAL_ORDERS,
	CASE
		WHEN TOTAL_ORDERS = 1 THEN 'One-Time Buyer'
		WHEN TOTAL_ORDERS BETWEEN 2 AND 4  THEN 'Occasional Buyer'
		ELSE 'Frequent Buyer'
	END AS CUSTOMER_CATEGORY
FROM
	ORDER_COUNTS;

--Find Revenue Contribution by Genre With Percentage Share
WITH
	GENRE_REVENUE AS (
		SELECT
			B.GENRE,
			SUM(O.TOTAL_AMOUNT) AS REVENUE
		FROM
			ORDERS O
			JOIN BOOKS B ON O.BOOK_ID = B.BOOK_ID
		GROUP BY
			B.GENRE
	),
	TOTAL_REV AS (
		SELECT
			SUM(REVENUE) AS GRAND_TOTAL
		FROM
			GENRE_REVENUE
	)
SELECT
	G.GENRE,
	G.REVENUE,
	ROUND((G.REVENUE / T.GRAND_TOTAL) * 100, 2) AS PERCENTAGE_SHARE
FROM
	GENRE_REVENUE G
	CROSS JOIN TOTAL_REV T
ORDER BY
	PERCENTAGE_SHARE DESC;

--Detect Declining Sales Books (Trend Analysis)
WITH
	MONTHLY_BOOK_SALES AS (
		SELECT
			B.BOOK_ID,
			B.TITLE,
			DATE_TRUNC('month', O.ORDER_DATE) AS MONTH,
			SUM(O.QUANTITY) AS MONTHLY_SALES
		FROM
			ORDERS O
			JOIN BOOKS B ON O.BOOK_ID = B.BOOK_ID
		GROUP BY
			B.BOOK_ID,
			B.TITLE,
			MONTH
	)
SELECT
	BOOK_ID,
	TITLE,
	MONTH,
	MONTHLY_SALES,
	LAG(MONTHLY_SALES) OVER (
		PARTITION BY
			BOOK_ID
		ORDER BY
			MONTH
	) AS PREVIOUS_MONTH_SALES
FROM
	MONTHLY_BOOK_SALES;

--Identify Customers Whose Spending Is Above Overall Average
WITH
	CUSTOMER_TOTALS AS (
		SELECT
			CUSTOMER_ID,
			SUM(TOTAL_AMOUNT) AS TOTAL_SPENT
		FROM
			ORDERS
		GROUP BY
			CUSTOMER_ID
	)
SELECT
	*
FROM
	CUSTOMER_TOTALS
WHERE
	TOTAL_SPENT > (
		SELECT
			AVG(TOTAL_SPENT)
		FROM
			CUSTOMER_TOTALS
	);

--Calculate Running Total Revenue Over Time
SELECT
	ORDER_DATE,
	SUM(TOTAL_AMOUNT) OVER (
		ORDER BY
			ORDER_DATE ROWS BETWEEN UNBOUNDED PRECEDING
			AND CURRENT ROW
	) AS CUMULATIVE_REVENUE
FROM
	ORDERS
ORDER BY
	ORDER_DATE;

--Find Inactive Customers
SELECT
	C.CUSTOMER_ID,
	C.NAME
FROM
	CUSTOMERS C
	LEFT JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE
	O.ORDER_ID IS NULL;

--Rank Authors by Revenue Within Each Genre
SELECT
	B.GENRE,
	B.AUTHOR,
	SUM(O.TOTAL_AMOUNT) AS TOTAL_REVENUE,
	RANK() OVER (
		PARTITION BY
			B.GENRE
		ORDER BY
			SUM(O.TOTAL_AMOUNT) DESC
	) AS AUTHOR_RANK
FROM
	BOOKS B
	JOIN ORDERS O ON B.BOOK_ID = O.BOOK_ID
GROUP BY
	B.GENRE,
	B.AUTHOR;